apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.44.8
  install:
    crds: Create
  interval: 1h0s
  upgrade:
    crds: Create
  targetNamespace: render-metrics-v1
  dependsOn:
  - name: prometheus
  releaseName: grafana
  timeout: 2m0s
  values:
    ingress:
      enabled: true
      hosts:
      - grafana.localtest.me
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s"
    domain: grafana.localtest.me
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Editor
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        labelValue: "1"
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 256Mi
    podAnnotations:
      prometheus.io/scrape: "false"
    service:
      annotations:
        prometheus.io/scrape: "false"
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: prometheus
          type: prometheus
          url: http://prometheus-server.service-metrics-v1:80
          isDefault: true