apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- provider.yaml
- alerts.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/summary
      value:
        ":cow: production cluster"
  target:
    kind: Alert
    name: slack