apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/summary
      value:
        summary: "production cluster"
  target:
    kind: Alert
    name: alerts