apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- values.yaml
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/valuesFrom/-
      value:
        kind: ConfigMap
        name: service-metrics-v1-values-local
  target:
    kind: HelmRelease
    name: prometheus