---
# Source: exporter-weather/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-exporter-weather
  namespace: exporter-weather-development-v1
  labels:
    helm.sh/chart: exporter-weather-0.1.0
    app.kubernetes.io/name: exporter-weather
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: exporter-weather
      app.kubernetes.io/instance: app
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: exporter-weather
        app.kubernetes.io/instance: app
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: exporter-weather
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
          image: "ghcr.io/nullify005/exporter-weather:v0.1.1"
          imagePullPolicy: IfNotPresent
          command:
            - "/exporter-weather"
          args:
            - "watch"
            - "r3fup88"
            - "--interval"
            - "2m"
            - "--listen"
            - ":2112"
          livenessProbe:
            httpGet:
              path: /health
              port: 2112
          readinessProbe:
            httpGet:
              path: /health
              port: 2112
          resources:
            limits:
              memory: 32Mi
            requests:
              memory: 32Mi