apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: chat-hvac
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://github.com/nullify005/chat-hvac
  ref:
    branch: main
  ignore: |
    # exclude everything
    /*
    # include the helm charts tho
    !/helm/