apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secrets.yaml
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/values/ingress/hosts
      value:
        - grafana.local
    - op: replace
      path: /spec/values/domain
      value:
        domain: grafana.local
    - op: add
      path: /spec/values/admin
      value:
        existingSecret: grafana
  target:
    kind: HelmRelease
    name: grafana