apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-intesis
  namespace: flux-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ./helm/charts/service-intesis
      sourceRef:
        kind: GitRepository
        name: service-intesis
        namespace: flux-system
      valuesFiles:
      - ./helm/charts/service-intesis/values.yaml
      - ./helm/values/app/common.yaml
      - ./helm/values/app/development.yaml
  targetNamespace: service-intesis-v1
  releaseName: service-intesis
  timeout: 2m0s
  values:
    image:
      tag: v0.2.3 # {"$imagepolicy": "flux-system:service-intesis:tag"}
