---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-external-mdns
  namespace: service-mdns-v1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-external-mdns
subjects:
- kind: ServiceAccount
  name: app-external-mdns
  namespace: service-mdns-v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-external-mdns
  namespace: service-mdns-v1
rules:
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - list
      - watch
    - apiGroups:
      - extensions
      - networking.k8s.io
      resources:
      - ingresses
      verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-external-mdns
  namespace: service-mdns-v1