{
 "title": "Weather",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(weather_humidity)/count(weather_humidity)",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "sum(weather_rain_since_9am_mm)/count(weather_rain_since_9am_mm)",
     "legendFormat": "mm rain since 9am"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(weather_temperature_celcius)/count(weather_temperature_celcius)",
     "legendFormat": "Temperature"
    },
    {
     "expr": "sum(weather_temperature_feelslike_celcius)/count(weather_temperature_feelslike_celcius)",
     "legendFormat": "Feels Like"
    }
   ]
  },
  {
   "title": "Windspeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "sum(weather_windspeed_kph)/count(weather_windspeed_kph)",
     "legendFormat": "Windspeed"
    },
    {
     "expr": "sum(weather_windspeed_gust_kph)/count(weather_windspeed_gust_kph)",
     "legendFormat": "Gusts"
    }
   ]
  },
  {
   "title": "HVAC Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(hvac_temperature_celcius{namespace=\"service-intesis-development-v1\"})/count(hvac_temperature_celcius{namespace=\"service-intesis-development-v1\"})",
     "legendFormat": "Temperature"
    },
    {
     "expr": "sum(hvac_setpoint_celcius{namespace=\"service-intesis-development-v1\"})/count(hvac_setpoint_celcius{namespace=\"service-intesis-development-v1\"})",
     "legendFormat": "SetPoint"
    }
   ]
  },
  {
   "title": "HVAC Power State",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hvac_power_state{namespace=\"service-intesis-development-v1\"})/count(hvac_power_state{namespace=\"service-intesis-development-v1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HVAC Mode State",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hvac_mode_state{namespace=\"service-intesis-development-v1\"})/count(hvac_mode_state{namespace=\"service-intesis-development-v1\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}