apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgCDL6eT5QGH0IqwWZPhCqVNdlTdkEYB6Ef1728e6mgLs9NPJ/BtolTEMwQUWN5gfNU6qprDk4mNMgmXRGnqIhL51iXNiKn7hdjo8rZDvkfBFpCiGoiKrgMjs26827Y+h3Mfs4wTre1YW4GnxHyVNuJll0iZNw+1hl7korwrtkrDvrqjckooxXHLKsOwplHUQC9MI4TYGfMM9OTKbj6tGK33Bvw/PZRUGAZuAXVv8dOm/ZB9E9dIYbtdxz6whQbf6wBrEzcyCIEu7Qfjdz4g+7vOzxK83D7S7MreCwfWSxkPKYghuIotSCfalRKuuak2sW2JkQ//bko7FJTGxXJUFMsB9kZQsF5/CRzAhHf1RwR3JCO+I4EtzDY1DYFvhqqDs53TbIzcTZD8DX3b1n8qvCSVt6XkqB78b1MQXmHQQG9fHAoJ9AUcWbtl3OW5+5TnYjybbkIWIw4AXMds0G5O9ghPecFsm5XX0pMv2Nlp1IGuWrBXbW1w5T4cvhQRhKz5OmyJ5SEYs0nNOmoccZLWlZF3g17G1SZFObX0UVEQTgifaAnkrGG64twdVIbT9Hk1aCe6RqRcfsf6R8kfqeqvFUtKgOxqSLhxev/e2O4zDSyIFNlXj3XCw16sxkYh8D38USadn2yypQr8/vY7LggxFSVLBCi08Rn2/P3HC0bLFsubqwIVGi6vHjQEzbA8k9l/OuDfOF2i4AdB6nqmlzzo9779ailrA/ZV7qA3TwN+I1fOJFmYT/cC+RYCue2d19zRc6bAiE8WxBogFUtya9mfRKZ4KSEWhG6r4CeBbsVYaTIYHA8=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: flux-system
    type: Opaque