apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 15.18.0
  install:
    crds: Create
  interval: 1h0s
  upgrade:
    crds: Create
  targetNamespace: service-metrics-v1
  releaseName: prometheus
  timeout: 2m0s
  valuesFrom:
  - kind: ConfigMap
    name: service-metrics-v1-values-common