apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snmp-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-snmp-exporter
      reconcileStrategy: ChartVersion
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: Create
  interval: 1h0s
  upgrade:
    crds: Create
  targetNamespace: exporter-snmp-v1
  releaseName: snmp-exporter
  timeout: 2m0s
  dependsOn:
  - name: prometheus
  valuesFrom:
  - kind: ConfigMap
    name: exporter-snmp-v1-values-common
  values:
    serviceAccount:
      create: false
    resources:
      requests:
        memory: 64Mi
      limits:
        memory: 64Mi
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
      runAsNonRoot: true